DROP TABLE IF EXISTS title_decompositions;

CREATE TABLE title_decompositions (
    id             INTEGER PRIMARY KEY,
    symbol         TEXT NOT NULL COLLATE NOCASE CHECK (length(symbol) BETWEEN 1 AND 14),
    titlePart      TEXT NOT NULL CHECK (length(trim(titlePart)) > 0),
    base_scope     TEXT NOT NULL CHECK (length(trim(base_scope)) > 0),
    excluded_scope TEXT NOT NULL CHECK (length(trim(excluded_scope)) > 0),
    UNIQUE (symbol, titlePart)
);

INSERT INTO title_decompositions(id, symbol, titlePart, base_scope, excluded_scope) VALUES
    (
        1, 'D07', 'CABLES OTHER THAN ELECTRIC', 'CABLES', 'ELECTRIC CABLES'
    ),
    (
        2,
        'G03',
        'ANALOGOUS TECHNIQUES USING WAVES OTHER THAN OPTICAL WAVES',
        'ANALOGOUS TECHNIQUES USING WAVES',
        'TECHNIQUES USING OPTICAL WAVES'
    ),
    (
        3, 'B26F', 'SEVERING BY MEANS OTHER THAN CUTTING', 'SEVERING BY ANY MEANS', 'SEVERING BY CUTTING'
    ),
    (
        4,
        'C07F',
        'ACYCLIC, CARBOCYCLIC, OR HETEROCYCLIC COMPOUNDS CONTAINING ELEMENTS OTHER THAN CARBON, HYDROGEN, HALOGEN, OXYGEN, NITROGEN, SULFUR, SELENIUM OR TELLURIUM',
        'ACYCLIC, CARBOCYCLIC, OR HETEROCYCLIC COMPOUNDS',
        'COMPOUNDS CONTAINING CARBON, HYDROGEN, HALOGEN, OXYGEN, NITROGEN, SULFUR, SELENIUM OR TELLURIUM ELEMENTS ONLY'
    ),
    (
        5,
        'C09C',
        'TREATMENT OF INORGANIC MATERIALS, OTHER THAN FIBROUS FILLERS, TO ENHANCE THEIR PIGMENTING OR FILLING PROPERTIES',
        'TREATMENT OF INORGANIC MATERIALS TO ENHANCE THEIR PIGMENTING OR FILLING PROPERTIES',
        'TREATMENT OF FIBROUS FILLERS'
    ),
    (
        6,
        'C23G',
        'CLEANING OR DEGREASING OF METALLIC MATERIAL BY CHEMICAL METHODS OTHER THAN ELECTROLYSIS',
        'CLEANING OR DEGREASING OF METALLIC MATERIAL BY CHEMICAL METHODS',
        'CLEANING OR DEGREASING BY ELECTROLYSIS'
    ),
    (
        7,
        'F02P',
        'IGNITION, OTHER THAN COMPRESSION IGNITION, FOR INTERNAL-COMBUSTION ENGINES',
        'IGNITION FOR INTERNAL-COMBUSTION ENGINES',
        'COMPRESSION IGNITION'
    ),
    (
        8,
        'F16C',
        'ROTARY ENGINEERING ELEMENTS OTHER THAN GEARING, COUPLING, CLUTCH OR BRAKE ELEMENTS',
        'ROTARY ENGINEERING ELEMENTS',
        'GEARING, COUPLING, CLUTCH OR BRAKE ELEMENTS'
    ),
    (
        9,
        'G03B',
        'APPARATUS OR ARRANGEMENTS EMPLOYING ANALOGOUS TECHNIQUES USING WAVES OTHER THAN OPTICAL WAVES',
        'APPARATUS OR ARRANGEMENTS EMPLOYING ANALOGOUS TECHNIQUES USING WAVES',
        'TECHNIQUES USING OPTICAL WAVES'
    ),
    (
        10,
        'H01S',
        'DEVICES USING STIMULATED EMISSION OF ELECTROMAGNETIC RADIATION IN WAVE RANGES OTHER THAN OPTICAL',
        'DEVICES USING STIMULATED EMISSION OF ELECTROMAGNETIC RADIATION',
        'STIMULATED EMISSION OF ELECTROMAGNETIC RADIATION IN OPTICAL RANGE'
    )
